name: CVE Dependency Scan

concurrency:
  group: dependency-check-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # run on the first day of each month

jobs:
  dependency-check:
    uses: tastyworks/boulangerie-shared-github-workflows/.github/workflows/dependency-check.yml@main
    secrets: inherit
