name: Pull Request Check

concurrency:
  group: pull-request-check-${{ github.ref }}
  cancel-in-progress: true

on:
  merge_group:
  pull_request:
    types:
      # defaults
      - opened
      - reopened
      - synchronize
      # add transition from draft to ready_for_review
      - ready_for_review

jobs:
  check:
    uses: tastyworks/boulangerie-shared-github-workflows/.github/workflows/check.yml@main
    secrets: inherit
