name: Release
run-name: On ${{ github.ref_name }}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  release:
    uses: tastyworks/boulangerie-shared-github-workflows/.github/workflows/release.yml@main
    secrets: inherit
