name: snapshot tag release on master

concurrency:
  group: ci-master
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
      - 'main'
      - '*.x'

jobs:
  snapshot-tag-release:
    uses: tastyworks/boulangerie-shared-github-workflows/.github/workflows/snapshot-tag-release-on-master.yml@main
    secrets: inherit
