name: setup
description: setup for boulangerie java workflows

inputs:
  GH_ACCESS_TOKEN:
    description: Github Access Token
    required: true
  JAVA_DISTRIBUTION:
    description: 'https://github.com/actions/setup-java#supported-distributions'
    required: false
    default: 'temurin'
  GRADLE_SCRIPTS_PATH:
    description: 'Path to clone gradle-scripts into'
    required: false
    default: 'gradle-scripts'
  WITH_DOCKER:
    description: Whether or not to setup docker
    required: false
    default: 'false'
  DOCKER_USER:
    description: Docker user
    required: false
  DOCKER_PASSWORD:
    description: Docker password
    required: false
  WITH_DYNAMODB:
    description: dynamodb-test-lib-java
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.GH_ACCESS_TOKEN }}
        path: project
        submodules: true

    - name: Clone gradle-scripts
      uses: actions/checkout@v4
      with:
        repository: tastyworks/gradle-scripts
        token: ${{ inputs.GH_ACCESS_TOKEN }}
        path: ${{ inputs.GRADLE_SCRIPTS_PATH }}

    - name: Checkout dynamodb-test-lib
      if: ${{ inputs.WITH_DYNAMODB == true }}
      uses: actions/checkout@v4
      with:
        repository: tastyworks/tastyworks-dynamodb-test-lib-java
        token: ${{ inputs.GH_ACCESS_TOKEN }}
        path: tastyworks-dynamodb-test-lib-java

    - name: Read .java-version
      shell: bash
      run: |
        echo "JAVA_VERSION=$(cat project/.java-version)" >> $GITHUB_ENV

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Login to Docker Hub
      if: ${{ inputs.WITH_DOCKER == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKER_USER }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    - name: Set up QEMU
      if: ${{ inputs.WITH_DOCKER == 'true' }}
      uses: docker/setup-qemu-action@v3
