name: setup
description: setup for boulangerie java workflows

inputs:
  GH_ACCESS_TOKEN:
    description: Github Access Token
    required: true
  JAVA_DISTRIBUTION:
    description: 'https://github.com/actions/setup-java#supported-distributions'
    required: false
    default: 'temurin'
  GRADLE_SCRIPTS_PATH:
    description: 'Path to clone gradle-scripts into'
    required: false
    default: 'gradle-scripts'

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.GH_ACCESS_TOKEN }}
        path: project

    - name: Clone gradle-scripts
      uses: actions/checkout@v4
      with:
        repository: tastyworks/gradle-scripts
        token: ${{ inputs.GH_ACCESS_TOKEN }}
        path: ${{ inputs.GRADLE_SCRIPTS_PATH }}

    - name: Read .java-version
      shell: bash
      run: |
        echo "JAVA_VERSION=$(cat project/.java-version)" >> $GITHUB_ENV

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

