name: Setup docker
description: Setup docker stuff

runs:
  using: 'composite'
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_VAST_USER }}
        password: ${{ secrets.DOCKER_HUB_VAST_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

