name: Docker Build and Push Java
description: Build and push Docker images for Java projects using Docker CLI

inputs:
  VERSION_TAG:
    description: 'Version tag for the Docker image'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get Gradle project name and version
      id: gradle-info
      shell: bash
      working-directory: ./project
      run: |
        # Extract project name from settings.gradle or settings.gradle.kts
        if [ -f "settings.gradle" ]; then
          PROJECT_NAME=$(grep -E "rootProject\.name\s*=\s*['\"]([^'\"]+)['\"]" settings.gradle | sed -E "s/.*['\"]([^'\"]+)['\"].*/\1/")
        elif [ -f "settings.gradle.kts" ]; then
          PROJECT_NAME=$(grep -E "rootProject\.name\s*=\s*\"([^\"]+)\"" settings.gradle.kts | sed -E "s/.*\"([^\"]+)\".*/\1/")
        else
          echo "No settings.gradle or settings.gradle.kts found"
          exit 1
        fi
        
        echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_OUTPUT
        echo "Project name: ${PROJECT_NAME}"

    - name: Build JAR with Gradle
      shell: bash
      working-directory: ./project
      run: |
        ./gradlew installDist \
          -Pversion=${{ inputs.VERSION_TAG }} \
          -PAWS_MAVEN_ACCESS_KEY_ID=${AWS_MAVEN_ACCESS_KEY_ID} \
          -PAWS_MAVEN_ACCESS_SECRET_KEY=${AWS_MAVEN_ACCESS_SECRET_KEY}
        
        cp Dockerfile ./project/build/install/${{ steps.gradle-info.outputs.PROJECT_NAME }}/Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./project/build/install/${{ steps.gradle-info.outputs.PROJECT_NAME }
        platforms: linux/arm64
        push: true
        tags: "tastyworks/${{ steps.gradle-info.outputs.PROJECT_NAME }}:${{ inputs.VERSION_TAG }}"
        build-args: |
          GITHUB_TOKEN=${{ env.GH_ACCESS_TOKEN }}
          AWS_MAVEN_ACCESS_KEY_ID=${{ env.AWS_MAVEN_ACCESS_KEY_ID }}
          AWS_MAVEN_ACCESS_SECRET_KEY=${{ env.AWS_MAVEN_ACCESS_SECRET_KEY }}