name: Continuous Release

on:
  workflow_call:
    secrets:
      AWS_MAVEN_ACCESS_KEY_ID:
        required: true
      AWS_MAVEN_ACCESS_SECRET_KEY:
        required: true
      DOCKER_HUB_VAST_USER:
        required: true
      DOCKER_HUB_VAST_PASSWORD:
        required: true
      GH_ACCESS_TOKEN:
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: anothrNick/github-tag-action@1.67.0
        id: bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: false
    outputs:
      new-tag: ${{ steps.bump-version.outputs.new_tag }}
  docker-push:
    needs: bump-version
    runs-on: ubuntu-22.04
    steps:
      - uses: tastyworks/boulangerie-shared-github-workflows/.github/common-setup@main
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_VAST_USER }}
          password: ${{ secrets.DOCKER_HUB_VAST_PASSWORD }}
      - name: Push Docker
        working-directory: ./project
        run: |
          ./gradlew \
            -Pversion=${{ needs.bump-version.outputs.new-tag }} \
            -PAWS_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_ACCESS_KEY_ID }} \
            -PAWS_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_ACCESS_SECRET_KEY }} \
            dockerPush
