name: Continuously Release

on:
  workflow_call:
    secrets:
      AWS_MAVEN_ACCESS_KEY_ID:
        required: true
      AWS_MAVEN_ACCESS_SECRET_KEY:
        required: true
      AWS_MAVEN_PUBLISH_KEY_ID:
        required: true
      AWS_MAVEN_PUBLISH_SECRET_KEY:
        required: true
      GH_ACCESS_TOKEN:
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anothrNick/github-tag-action@1.67.0
        id: bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: false
    outputs:
      new-tag: ${{ steps.bump-version.outputs.new_tag }}
  publish:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: tastyworks/boulangerie-shared-github-workflows/.github/common-setup@main
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Publish
        working-directory: ./project
        run: |
          ./gradlew \
            -PAWS_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_ACCESS_KEY_ID }} \
            -PAWS_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_ACCESS_SECRET_KEY }} \
            -PAWS_MAVEN_PUBLISH_KEY_ID=${{ secrets.AWS_MAVEN_PUBLISH_KEY_ID }} \
            -PAWS_MAVEN_PUBLISH_SECRET_KEY=${{ secrets.AWS_MAVEN_PUBLISH_SECRET_KEY }} \
            -Pversion=${{ needs.bump-version.outputs.new-tag }} \
            publish