name: Create and push Java server image to Docker Hub

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      AWS_MAVEN_ACCESS_KEY_ID:
        required: true
      AWS_MAVEN_ACCESS_SECRET_KEY:
        required: true
      DOCKER_HUB_VAST_USER:
        required: true
      DOCKER_HUB_VAST_PASSWORD:
        required: true

jobs:
  should-continue:
    runs-on: ubuntu-22.04
    steps:
      - name: Check if ref is a tag and not a snapshot
        id: check
        run: |
          echo "IS_TAG=false" >> $GITHUB_ENV
          echo "IS_NOT_SNAPSHOT=false" >> $GITHUB_ENV
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "IS_TAG=true" >> $GITHUB_ENV
          fi
          if [[ "${{ github.ref_name }}" != *"-SNAPSHOT" ]]; then
            echo "IS_NOT_SNAPSHOT=true" >> $GITHUB_ENV
          fi
      - name: Set output
        id: output
        run: |
          if [[ "${{ env.IS_TAG }}" == "true" && "${{ env.IS_NOT_SNAPSHOT }}" == "true" ]]; then
            echo "should-continue=true" >> $GITHUB_ENV
          else
            echo "should-continue=false" >> $GITHUB_ENV
          fi
    outputs:
      should-continue: ${{ env.should-continue }}

  push_to_docker_hub:
    needs: should-continue
    if: ${{ needs.should-continue.outputs.should-continue == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: tastyworks/boulangerie-shared-github-workflows/.github/common-setup@main
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_VAST_USER }}
          password: ${{ secrets.DOCKER_HUB_VAST_PASSWORD }}

      - name: Push to Docker Hub
        working-directory: ./project
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-user-static
          ./gradlew \
          -PAWS_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_ACCESS_KEY_ID }} \
          -PAWS_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_ACCESS_SECRET_KEY }} \
          dockerPush