name: Create VAST Docker Image Java

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      AWS_MAVEN_ACCESS_KEY_ID:
        required: true
      AWS_MAVEN_ACCESS_SECRET_KEY:
        required: true
      VAST_ECR_PUBLISHER_KEY:
        required: true
      VAST_ECR_PUBLISHER_SECRET:
        required: true

jobs:
  create-vast-docker-image-java:
    runs-on: ubuntu-latest

    steps:
      - uses: tastyworks/boulangerie-shared-github-workflows/.github/common-setup@main
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.VAST_ECR_PUBLISHER_KEY}}
          aws-secret-access-key: ${{secrets.VAST_ECR_PUBLISHER_SECRET}}
          aws-region: us-east-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to ECR
        working-directory: ./project
        run: >
          ./gradlew
          -PAWS_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_ACCESS_KEY_ID }}
          -PAWS_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_ACCESS_SECRET_KEY }}
          dockerPush

