name: Create and push Java server image to Docker Hub

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      AWS_MAVEN_ACCESS_KEY_ID:
        required: true
      AWS_MAVEN_ACCESS_SECRET_KEY:
        required: true
      DOCKER_HUB_VAST_USER:
        required: true
      DOCKER_HUB_VAST_PASSWORD:
        required: true

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - uses: tastyworks/boulangerie-shared-github-workflows/.github/common-setup@main
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_VAST_USER }}
          password: ${{ secrets.DOCKER_HUB_VAST_PASSWORD }}

      - name: Push to Docker Hub
        working-directory: ./project
        run: >
          ./gradlew
          -PAWS_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_ACCESS_KEY_ID }}
          -PAWS_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_ACCESS_SECRET_KEY }}
          dockerPush