name: Lint Github Action YAML files

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
    paths:
      - '.github/**/*.yml'
      - 'sample usage/**/*.yml'

jobs:
  lint-github-actions:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install action-validator
        uses: asdf-vm/actions/install@v4
        with:
          tool_versions: |
            action-validator 0.7.0

      - name: Lint
        run: |
          find .github -type f -iname \*.yml | xargs -I {} action-validator --verbose {}
