name: Pull Request Check

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      AWS_MAVEN_ACCESS_KEY_ID:
        required: true
      AWS_MAVEN_ACCESS_SECRET_KEY:
        required: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/common-setup
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Gradle Check
        working-directory: ./project
        run: >
          ./gradlew
          -PTW_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_ACCESS_KEY_ID }}
          -PTW_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_ACCESS_SECRET_KEY }}
          check
