# deprecated (use check.yml instead)
name: Pull Request Check

on:
  workflow_call:
    inputs:
      GRADLE_SCRIPTS_PATH:
        description: 'Path to clone gradle-scripts into'
        type: string
        required: false
        default: 'gradle-scripts'
      DOCKER_USER:
        description: Docker user
        required: false
        type: string
      DOCKER_PASSWORD:
        description: Docker password
        required: false
        type: string
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      AWS_MAVEN_ACCESS_KEY_ID:
        required: true
      AWS_MAVEN_ACCESS_SECRET_KEY:
        required: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: tastyworks/boulangerie-shared-github-workflows/.github/common-setup@main
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GRADLE_SCRIPTS_PATH: ${{ inputs.GRADLE_SCRIPTS_PATH }}
          DOCKER_USER: ${{ inputs.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ inputs.DOCKER_PASSWORD }}

      - name: Gradle Check
        working-directory: ./project
        run: >
          ./gradlew
          -PTW_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_ACCESS_KEY_ID }}
          -PTW_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_ACCESS_SECRET_KEY }}
          check
