# deprecated (use check.yml instead)
name: Pull Request Check

permissions:
  checks: write

on:
  workflow_call:
    inputs:
      GRADLE_SCRIPTS_PATH:
        description: 'Path to clone gradle-scripts into'
        type: string
        required: false
        default: 'gradle-scripts'
      WITH_DOCKER:
        description: Docker user
        required: false
        type: boolean
        default: false
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      AWS_MAVEN_ACCESS_KEY_ID:
        required: true
      AWS_MAVEN_ACCESS_SECRET_KEY:
        required: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: tastyworks/boulangerie-shared-github-workflows/.github/common-setup@main
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          GRADLE_SCRIPTS_PATH: ${{ inputs.GRADLE_SCRIPTS_PATH }}
          WITH_DOCKER: ${{ inputs.WITH_DOCKER }}
          DOCKER_USER: ${{ secrets.DOCKER_HUB_VAST_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_VAST_PASSWORD }}

      - name: Gradle Check
        working-directory: ./project
        run: >
          ./gradlew
          -PTW_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_ACCESS_KEY_ID }}
          -PTW_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_ACCESS_SECRET_KEY }}
          check
