name: Release

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      AWS_MAVEN_PUBLISH_KEY_ID:
        required: true
      AWS_MAVEN_PUBLISH_SECRET_KEY:
        required: true
    inputs:
      gradle-args:
        description: 'Additional arguments to gradle'
        default: ''
        required: false
        type: string
      WITH_DOCKER:
        description: Docker user
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: tastyworks/boulangerie-shared-github-workflows/.github/common-setup@main
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          WITH_DOCKER: ${{ inputs.WITH_DOCKER }}
          DOCKER_USER: ${{ secrets.DOCKER_HUB_VAST_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_VAST_PASSWORD }}

      - name: Setup git config
        working-directory: ./project
        env:
          USER_NAME: ${{ github.event.sender.login }}
        run: |
          git config user.name $USER_NAME
          git config user.email "<>"

      - name: Gradle Auto Release
        working-directory: ./project
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: >
          ./gradlew
          -PTW_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_PUBLISH_KEY_ID }}
          -PTW_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_PUBLISH_SECRET_KEY }}
          doReleaseImmediate
          ${{ inputs.gradle-args }}
