name: Release

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      AWS_MAVEN_PUBLISH_KEY_ID:
        required: true
      AWS_MAVEN_PUBLISH_SECRET_KEY:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: project

      - name: Clone gradle-scripts
        uses: actions/checkout@v3
        with:
          repository: tastyworks/gradle-scripts
          ref: 'RefactorBoulangerieReleaseProcess'
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: gradle-scripts

      - name: Read .java-version
        run: |
          echo "JAVA_VERSION=$(cat project/.java-version)" >> $GITHUB_ENV

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup git config
        working-directory: ./project
        env:
          USER_NAME: ${{ github.event.sender.login }}
        run: |
          git config user.name $USER_NAME
          git config user.email "<>"

      - name: Gradle Auto Release
        working-directory: ./project
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: >
          ./gradlew
          -PTW_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_PUBLISH_KEY_ID }}
          -PTW_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_PUBLISH_SECRET_KEY }}
          doReleaseImmediate
