name: Snapshot Tag Release On Master

concurrency:
  group: snapshot-tag-release-on-master
  cancel-in-progress: true

on:
  workflow_call:
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      AWS_MAVEN_PUBLISH_KEY_ID:
        required: true
      AWS_MAVEN_PUBLISH_SECRET_KEY:
        required: true

jobs:
  snapshot-tag-release-on-master:
    runs-on: ubuntu-latest
      - uses: ./.github/common-setup
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Gradle Snapshot Tag/Release
        working-directory: ./project
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: >
          ./gradlew
          -PTW_MAVEN_ACCESS_KEY_ID=${{ secrets.AWS_MAVEN_PUBLISH_KEY_ID }}
          -PTW_MAVEN_ACCESS_SECRET_KEY=${{ secrets.AWS_MAVEN_PUBLISH_SECRET_KEY }}
          doSnapshotTagAndRelease
